// Generated by Haxe 4.1.1
#ifndef INCLUDED_maglev__MagLevTypes_MagLevType_Impl_
#define INCLUDED_maglev__MagLevTypes_MagLevType_Impl_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(maglev,_MagLevTypes,MagLevType_Impl_)

namespace maglev{
namespace _MagLevTypes{


class HXCPP_CLASS_ATTRIBUTES MagLevType_Impl__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef MagLevType_Impl__obj OBJ_;
		MagLevType_Impl__obj();

	public:
		enum { _hx_ClassId = 0x2cf8e4fe };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="maglev._MagLevTypes.MagLevType_Impl_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"maglev._MagLevTypes.MagLevType_Impl_"); }

		inline static ::hx::ObjectPtr< MagLevType_Impl__obj > __new() {
			::hx::ObjectPtr< MagLevType_Impl__obj > __this = new MagLevType_Impl__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< MagLevType_Impl__obj > __alloc(::hx::Ctx *_hx_ctx) {
			MagLevType_Impl__obj *__this = (MagLevType_Impl__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(MagLevType_Impl__obj), false, "maglev._MagLevTypes.MagLevType_Impl_"));
			*(void **)__this = MagLevType_Impl__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~MagLevType_Impl__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("MagLevType_Impl_",a4,5e,de,43); }

		static void __boot();
		static int MagLevType_Result;
		static int MagLevType_Error;
		static int MagLevType_Function;
		static int MagLevType_Object;
		static int MagLevType_Array;
		static int MagLevType_Number;
		static int MagLevType_String;
		static int MagLevType_Boolean;
		static int MagLevType_Null;
		static int _new(int i);
		static ::Dynamic _new_dyn();

};

} // end namespace maglev
} // end namespace _MagLevTypes

#endif /* INCLUDED_maglev__MagLevTypes_MagLevType_Impl_ */ 
