// Generated by Haxe 4.1.1
#ifndef INCLUDED_maglev_MagLevType
#define INCLUDED_maglev_MagLevType

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(maglev,MagLevType)
namespace maglev{


class MagLevType_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef MagLevType_obj OBJ_;

	public:
		MagLevType_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("maglev.MagLevType",c8,c9,51,f3); }
		::String __ToString() const { return HX_("MagLevType.",aa,1c,46,bd) + _hx_tag; }

		static ::maglev::MagLevType MagLevType_Array;
		static inline ::maglev::MagLevType MagLevType_Array_dyn() { return MagLevType_Array; }
		static ::maglev::MagLevType MagLevType_Boolean;
		static inline ::maglev::MagLevType MagLevType_Boolean_dyn() { return MagLevType_Boolean; }
		static ::maglev::MagLevType MagLevType_Error;
		static inline ::maglev::MagLevType MagLevType_Error_dyn() { return MagLevType_Error; }
		static ::maglev::MagLevType MagLevType_Function;
		static inline ::maglev::MagLevType MagLevType_Function_dyn() { return MagLevType_Function; }
		static ::maglev::MagLevType MagLevType_Null;
		static inline ::maglev::MagLevType MagLevType_Null_dyn() { return MagLevType_Null; }
		static ::maglev::MagLevType MagLevType_Number;
		static inline ::maglev::MagLevType MagLevType_Number_dyn() { return MagLevType_Number; }
		static ::maglev::MagLevType MagLevType_Object;
		static inline ::maglev::MagLevType MagLevType_Object_dyn() { return MagLevType_Object; }
		static ::maglev::MagLevType MagLevType_Result;
		static inline ::maglev::MagLevType MagLevType_Result_dyn() { return MagLevType_Result; }
		static ::maglev::MagLevType MagLevType_String;
		static inline ::maglev::MagLevType MagLevType_String_dyn() { return MagLevType_String; }
};

} // end namespace maglev

#endif /* INCLUDED_maglev_MagLevType */ 
