// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_869a921fcf5bba54
#define INCLUDED_869a921fcf5bba54
#include "maglev/MagLevAny.h"
#endif
#ifndef INCLUDED_20db69a30a45e926
#define INCLUDED_20db69a30a45e926
#include "maglev/MagLevArray.h"
#endif
#ifndef INCLUDED_35ec03520fbb0747
#define INCLUDED_35ec03520fbb0747
#include "maglev/MagLevBoolean.h"
#endif
#ifndef INCLUDED_7f9204b932c8d809
#define INCLUDED_7f9204b932c8d809
#include "maglev/MagLevFunction.h"
#endif
#ifndef INCLUDED_ba46386e6aba7150
#define INCLUDED_ba46386e6aba7150
#include "maglev/MagLevNull.h"
#endif
#ifndef INCLUDED_95fa5e9194badcf5
#define INCLUDED_95fa5e9194badcf5
#include "maglev/MagLevNumber.h"
#endif
#ifndef INCLUDED_f4da16f85a617f60
#define INCLUDED_f4da16f85a617f60
#include "maglev/MagLevObject.h"
#endif
#ifndef INCLUDED_65acb6100057af6e
#define INCLUDED_65acb6100057af6e
#include "maglev/MagLevResult.h"
#endif
#ifndef INCLUDED_c859d2752ef86c43
#define INCLUDED_c859d2752ef86c43
#include "maglev/MagLevString.h"
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_persistence_Persistence
#include <persistence/Persistence.h>
#endif
#ifndef INCLUDED_persistence__Persistence_Getter
#include <persistence/_Persistence/Getter.h>
#endif
#ifndef INCLUDED_persistence__Persistence_Mutator
#include <persistence/_Persistence/Mutator.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_20_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",20,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_35_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",35,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_54_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",54,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_61_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",61,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_16_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",16,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_70_addMutator,"persistence.Persistence","addMutator",0xab434ebf,"persistence.Persistence.addMutator","persistence/Persistence.hx",70,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_72_addMutator,"persistence.Persistence","addMutator",0xab434ebf,"persistence.Persistence.addMutator","persistence/Persistence.hx",72,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_81_addGetter,"persistence.Persistence","addGetter",0xa800a5ce,"persistence.Persistence.addGetter","persistence/Persistence.hx",81,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_83_addGetter,"persistence.Persistence","addGetter",0xa800a5ce,"persistence.Persistence.addGetter","persistence/Persistence.hx",83,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_86_addGetter,"persistence.Persistence","addGetter",0xa800a5ce,"persistence.Persistence.addGetter","persistence/Persistence.hx",86,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_96_mutate,"persistence.Persistence","mutate",0x1e0a9484,"persistence.Persistence.mutate","persistence/Persistence.hx",96,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_136_get,"persistence.Persistence","get",0x1c3374d8,"persistence.Persistence.get","persistence/Persistence.hx",136,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_193_calcKey,"persistence.Persistence","calcKey",0xf23c314c,"persistence.Persistence.calcKey","persistence/Persistence.hx",193,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_197_convertToHaxe,"persistence.Persistence","convertToHaxe",0x4e912456,"persistence.Persistence.convertToHaxe","persistence/Persistence.hx",197,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_240_convertToMagLev,"persistence.Persistence","convertToMagLev",0xe4dcf33a,"persistence.Persistence.convertToMagLev","persistence/Persistence.hx",240,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_10_boot,"persistence.Persistence","boot",0x8d8c49b0,"persistence.Persistence.boot","persistence/Persistence.hx",10,0x9767c4cf)
namespace persistence{

void Persistence_obj::__construct( ::maglev::MagLev bus){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_20_new)
HXLINE(  21)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  22)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  23)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  23)			 ::Dynamic strategyMethod = _gthis1->convertToHaxe(args->get(2));
HXLINE(  24)			 ::Dynamic updateMapper = null();
HXLINE(  25)			if ((args->size() > 3)) {
HXLINE(  26)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  26)				updateMapper = _gthis1->convertToHaxe(args->get(3));
            			}
HXLINE(  28)			 ::Dynamic useRecordDataAsParams = null();
HXLINE(  29)			if ((args->size() > 4)) {
HXLINE(  30)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  30)				useRecordDataAsParams = _gthis1->convertToHaxe(args->get(4));
            			}
HXLINE(  32)			_gthis->addMutator(recordType,operationName,strategyMethod,updateMapper,useRecordDataAsParams);
HXLINE(  33)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevBoolean_obj::fromBool(true));
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_1, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_35_new)
HXLINE(  36)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  37)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  38)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  38)			 ::Dynamic strategyMethod = _gthis1->convertToHaxe(args->get(2));
HXLINE(  39)			 ::Dynamic queryMapper = null();
HXLINE(  40)			if ((args->size() >= 4)) {
HXLINE(  41)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  41)				queryMapper = _gthis1->convertToHaxe(args->get(3));
            			}
HXLINE(  43)			 ::Dynamic resultMapper = null();
HXLINE(  44)			if ((args->size() >= 5)) {
HXLINE(  45)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  45)				resultMapper = _gthis1->convertToHaxe(args->get(4));
            			}
HXLINE(  47)			 ::Dynamic useQueryValuesAsParams = null();
HXLINE(  48)			if ((args->size() >= 6)) {
HXLINE(  49)				useQueryValuesAsParams = ::hx::TCast<  ::maglev::MagLevBoolean >::cast(args->get(5))->getBool();
            			}
HXLINE(  51)			_gthis->addGetter(recordType,operationName,strategyMethod,queryMapper,resultMapper,useQueryValuesAsParams);
HXLINE(  52)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevBoolean_obj::fromBool(true));
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_54_new)
HXLINE(  55)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  56)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  57)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  57)			 ::Dynamic recordData = _gthis1->convertToHaxe(args->get(2));
HXLINE(  58)			_gthis->mutate(recordType,operationName,recordData);
HXLINE(  59)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevBoolean_obj::fromBool(true));
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_3, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_61_new)
HXLINE(  62)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  63)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  64)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  64)			 ::Dynamic queryValues = _gthis1->convertToHaxe(args->get(2));
HXLINE(  65)			 ::persistence::Persistence _gthis2 = _gthis;
HXDLIN(  65)			 ::maglev::MagLevAny ret = _gthis2->convertToMagLev(_gthis->get(recordType,operationName,queryValues));
HXLINE(  66)			return ::maglev::MagLevResult_obj::fromResult(ret);
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_16_new)
HXDLIN(  16)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE(  17)		this->mutators =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  18)		this->getters =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  19)		this->maglev = bus;
HXLINE(  20)		 ::maglev::MagLev _hx_tmp = this->maglev;
HXDLIN(  20)		_hx_tmp->_hx_register(HX_("Persistence.AddMutator",b0,4b,5e,d4),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_0(_gthis))));
HXLINE(  35)		 ::maglev::MagLev _hx_tmp1 = this->maglev;
HXDLIN(  35)		_hx_tmp1->_hx_register(HX_("Persistence.AddGetter",fd,51,1c,b7),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_1(_gthis))));
HXLINE(  54)		 ::maglev::MagLev _hx_tmp2 = this->maglev;
HXDLIN(  54)		_hx_tmp2->_hx_register(HX_("Persistence.Mutate",f5,04,66,8c),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_2(_gthis))));
HXLINE(  61)		 ::maglev::MagLev _hx_tmp3 = this->maglev;
HXDLIN(  61)		_hx_tmp3->_hx_register(HX_("Persistence.Get",c7,c3,56,12),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_3(_gthis))));
            	}

Dynamic Persistence_obj::__CreateEmpty() { return new Persistence_obj; }

void *Persistence_obj::_hx_vtable = 0;

Dynamic Persistence_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Persistence_obj > _hx_result = new Persistence_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Persistence_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x0263bb48;
}

void Persistence_obj::addMutator(::String recordType,::String operationName, ::Dynamic strategyMethod, ::Dynamic updateMapper, ::Dynamic useRecordDataAsParams){
            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_70_addMutator)
HXLINE(  71)		if (::hx::IsNull( updateMapper )) {
            			HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(1)
            			 ::Dynamic _hx_run( ::Dynamic v){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_72_addMutator)
HXLINE(  72)				return v;
            			}
            			HX_END_LOCAL_FUNC1(return)

HXLINE(  72)			updateMapper =  ::Dynamic(new _hx_Closure_0());
            		}
HXLINE(  74)		if (::hx::IsNull( useRecordDataAsParams )) {
HXLINE(  75)			useRecordDataAsParams = false;
            		}
HXLINE(  77)		 ::persistence::_Persistence::Mutator mutator =  ::persistence::_Persistence::Mutator_obj::__alloc( HX_CTX ,recordType,strategyMethod,updateMapper,( (bool)(useRecordDataAsParams) ));
HXLINE(  78)		{
HXLINE(  78)			::Dynamic this1 = this->mutators;
HXDLIN(  78)			( ( ::haxe::ds::StringMap)(this1) )->set(this->calcKey(recordType,operationName),mutator);
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC5(Persistence_obj,addMutator,(void))

void Persistence_obj::addGetter(::String recordType,::String operationName, ::Dynamic strategyMethod, ::Dynamic queryMapper, ::Dynamic resultMapper, ::Dynamic useQueryValuesAsParams){
            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_81_addGetter)
HXLINE(  82)		if (::hx::IsNull( queryMapper )) {
            			HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(1)
            			 ::Dynamic _hx_run( ::Dynamic v){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_83_addGetter)
HXLINE(  83)				return v;
            			}
            			HX_END_LOCAL_FUNC1(return)

HXLINE(  83)			queryMapper =  ::Dynamic(new _hx_Closure_0());
            		}
HXLINE(  85)		if (::hx::IsNull( resultMapper )) {
            			HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            			 ::Dynamic _hx_run( ::Dynamic v){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_86_addGetter)
HXLINE(  86)				return v;
            			}
            			HX_END_LOCAL_FUNC1(return)

HXLINE(  86)			resultMapper =  ::Dynamic(new _hx_Closure_1());
            		}
HXLINE(  88)		if (::hx::IsNull( useQueryValuesAsParams )) {
HXLINE(  89)			useQueryValuesAsParams = false;
            		}
HXLINE(  91)		 ::persistence::_Persistence::Getter getter =  ::persistence::_Persistence::Getter_obj::__alloc( HX_CTX ,recordType,strategyMethod,queryMapper,resultMapper,( (bool)(useQueryValuesAsParams) ));
HXLINE(  92)		{
HXLINE(  92)			::Dynamic this1 = this->getters;
HXDLIN(  92)			( ( ::haxe::ds::StringMap)(this1) )->set(this->calcKey(recordType,operationName),getter);
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC6(Persistence_obj,addGetter,(void))

void Persistence_obj::mutate(::String recordType,::String operationName, ::Dynamic recordData){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_96_mutate)
HXDLIN(  96)		::Dynamic this1 = this->mutators;
HXDLIN(  96)		if (( ( ::haxe::ds::StringMap)(this1) )->exists(this->calcKey(recordType,operationName))) {
HXLINE(  97)			::Dynamic this1 = this->mutators;
HXDLIN(  97)			 ::persistence::_Persistence::Mutator mutator = ( ( ::persistence::_Persistence::Mutator)(( ( ::haxe::ds::StringMap)(this1) )->get(this->calcKey(recordType,operationName))) );
HXLINE(  99)			 ::Dynamic params = null();
HXLINE( 100)			if (::Reflect_obj::isFunction(mutator->updateMapper)) {
HXLINE( 101)				 ::Dynamic updateMapper = mutator->updateMapper;
HXLINE( 102)				params = updateMapper(recordData);
            			}
            			else {
HXLINE( 104)				if (::Std_obj::isOfType(mutator->updateMapper,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
HXLINE( 105)					::String updateMapper = ( (::String)(mutator->updateMapper) );
HXLINE( 107)					 ::maglev::MagLev value = this->maglev;
HXDLIN( 107)					params = value->call(updateMapper,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,recordData))));
            				}
            				else {
HXLINE( 110)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("updateMapper must be a string or function",e1,0d,80,87)));
            				}
            			}
HXLINE( 113)			 ::Dynamic raw_result = null();
HXLINE( 114)			if (::Reflect_obj::isFunction(mutator->strategyMethod)) {
HXLINE( 115)				 ::Dynamic strategyMethod = mutator->strategyMethod;
HXLINE( 116)				raw_result = strategyMethod(params);
            			}
            			else {
HXLINE( 118)				if (::Std_obj::isOfType(mutator->strategyMethod,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
HXLINE( 119)					::String strategyMethod = ( (::String)(mutator->strategyMethod) );
HXLINE( 120)					if (mutator->useRecordDataAsParams) {
HXLINE( 121)						 ::maglev::MagLev value = this->maglev;
HXDLIN( 121)						raw_result = value->call(strategyMethod,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(params)));
            					}
            					else {
HXLINE( 123)						 ::maglev::MagLev value = this->maglev;
HXDLIN( 123)						raw_result = value->call(strategyMethod,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,params))));
            					}
            				}
            				else {
HXLINE( 127)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("strategyMethod must be a string or function",97,7a,0d,90)));
            				}
            			}
            		}
            		else {
HXLINE( 131)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("the specified mutator has not been added",fc,3b,68,3f)));
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,mutate,(void))

 ::Dynamic Persistence_obj::get(::String recordType,::String operationName, ::Dynamic queryValues){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_136_get)
HXDLIN( 136)		::Dynamic this1 = this->getters;
HXDLIN( 136)		if (( ( ::haxe::ds::StringMap)(this1) )->exists(this->calcKey(recordType,operationName))) {
HXLINE( 137)			::Dynamic this1 = this->getters;
HXDLIN( 137)			 ::persistence::_Persistence::Getter getter = ( ( ::persistence::_Persistence::Getter)(( ( ::haxe::ds::StringMap)(this1) )->get(this->calcKey(recordType,operationName))) );
HXLINE( 139)			 ::Dynamic query = null();
HXLINE( 140)			if (::Reflect_obj::isFunction(getter->queryMapper)) {
HXLINE( 141)				 ::Dynamic queryMapper = getter->queryMapper;
HXLINE( 142)				query = queryMapper(queryValues);
            			}
            			else {
HXLINE( 144)				if (::Std_obj::isOfType(getter->queryMapper,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
HXLINE( 145)					::String queryMapper = ( (::String)(getter->queryMapper) );
HXLINE( 147)					 ::maglev::MagLev value = this->maglev;
HXDLIN( 147)					query = value->call(queryMapper,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,queryValues))));
            				}
            				else {
HXLINE( 150)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("queryMapper must be a string or function",42,16,bc,ef)));
            				}
            			}
HXLINE( 153)			 ::Dynamic raw_result = null();
HXLINE( 154)			if (::Reflect_obj::isFunction(getter->strategyMethod)) {
HXLINE( 155)				 ::Dynamic strategyMethod = getter->strategyMethod;
HXLINE( 156)				raw_result = strategyMethod(query);
            			}
            			else {
HXLINE( 158)				if (::Std_obj::isOfType(getter->strategyMethod,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
HXLINE( 159)					::String strategyMethod = ( (::String)(getter->strategyMethod) );
HXLINE( 160)					if (getter->useQueryValuesAsParams) {
HXLINE( 161)						 ::maglev::MagLev raw_result_result = this->maglev;
HXDLIN( 161)						::String getter1 = ( (::String)(getter->strategyMethod) );
HXDLIN( 161)						 ::maglev::MagLevResult raw_result_result1 = raw_result_result->call(getter1,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(query)));
HXLINE( 162)						raw_result = this->convertToHaxe(raw_result_result1->getResult());
            					}
            					else {
HXLINE( 164)						 ::maglev::MagLev value = this->maglev;
HXDLIN( 164)						::String getter1 = ( (::String)(getter->strategyMethod) );
HXDLIN( 164)						raw_result = value->call(getter1,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,query))));
HXDLIN( 164)						 ::maglev::MagLevResult raw_result_result = ( ( ::maglev::MagLevResult)(raw_result) );
HXLINE( 165)						raw_result = this->convertToHaxe(raw_result_result->getResult());
            					}
            				}
            				else {
HXLINE( 169)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("strategyMethod must be a string or function",97,7a,0d,90)));
            				}
            			}
HXLINE( 172)			 ::Dynamic result = null();
HXLINE( 173)			if (::Reflect_obj::isFunction(getter->resultMapper)) {
HXLINE( 174)				 ::Dynamic resultMapper = getter->resultMapper;
HXLINE( 175)				result = resultMapper(raw_result);
            			}
            			else {
HXLINE( 177)				if (::Std_obj::isOfType(getter->resultMapper,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
HXLINE( 178)					::String resultMapper = ( (::String)(getter->resultMapper) );
HXLINE( 180)					 ::maglev::MagLev value = this->maglev;
HXDLIN( 180)					result = value->call(resultMapper,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,raw_result))));
            				}
            				else {
HXLINE( 183)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("resultMapper must be a string or function",8d,d7,71,1d)));
            				}
            			}
HXLINE( 185)			return result;
            		}
            		else {
HXLINE( 188)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("the specified getter has not been added",55,b4,c1,d8)));
            		}
HXLINE( 136)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,get,return )

::String Persistence_obj::calcKey(::String recordType,::String operationName){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_193_calcKey)
HXDLIN( 193)		return ((recordType + HX_(".",2e,00,00,00)) + operationName);
            	}


HX_DEFINE_DYNAMIC_FUNC2(Persistence_obj,calcKey,return )

 ::Dynamic Persistence_obj::convertToHaxe( ::maglev::MagLevAny x){
            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_197_convertToHaxe)
HXDLIN( 197)		int _hx_tmp = x->getType();
HXDLIN( 197)		if ((_hx_tmp == ::maglev::MagLevNull_obj::getStaticType())) {
HXLINE( 198)			return null();
            		}
            		else {
HXLINE( 200)			int _hx_tmp = x->getType();
HXDLIN( 200)			if ((_hx_tmp == ::maglev::MagLevBoolean_obj::getStaticType())) {
HXLINE( 201)				 ::maglev::MagLevBoolean y = ::hx::TCast<  ::maglev::MagLevBoolean >::cast(x);
HXLINE( 202)				return y->getBool();
            			}
            			else {
HXLINE( 204)				int _hx_tmp = x->getType();
HXDLIN( 204)				if ((_hx_tmp == ::maglev::MagLevString_obj::getStaticType())) {
HXLINE( 205)					 ::maglev::MagLevString y = ::hx::TCast<  ::maglev::MagLevString >::cast(x);
HXLINE( 206)					return y->getString();
            				}
            				else {
HXLINE( 208)					int _hx_tmp = x->getType();
HXDLIN( 208)					if ((_hx_tmp == ::maglev::MagLevNumber_obj::getStaticType())) {
HXLINE( 209)						 ::maglev::MagLevNumber y = ::hx::TCast<  ::maglev::MagLevNumber >::cast(x);
HXLINE( 210)						return y->getFloat();
            					}
            					else {
HXLINE( 212)						int _hx_tmp = x->getType();
HXDLIN( 212)						if ((_hx_tmp == ::maglev::MagLevArray_obj::getStaticType())) {
HXLINE( 213)							 ::maglev::MagLevArray y = ::hx::TCast<  ::maglev::MagLevArray >::cast(x);
HXLINE( 214)							::cpp::VirtualArray arr = ::cpp::VirtualArray_obj::__new();
HXLINE( 215)							int i = 0;
HXLINE( 216)							while((i < y->size())){
HXLINE( 217)								arr->push(this->convertToHaxe(y->get(i)));
HXLINE( 218)								i = (i + 1);
            							}
HXLINE( 220)							return arr;
            						}
            						else {
HXLINE( 222)							int _hx_tmp = x->getType();
HXDLIN( 222)							if ((_hx_tmp == ::maglev::MagLevObject_obj::getStaticType())) {
HXLINE( 223)								 ::maglev::MagLevObject y = ::hx::TCast<  ::maglev::MagLevObject >::cast(x);
HXLINE( 224)								 ::haxe::ds::StringMap map =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 225)								 ::maglev::MagLevArray keys = y->keys();
HXLINE( 226)								int i = 0;
HXLINE( 227)								while((i < keys->size())){
HXLINE( 228)									::String key = ::hx::TCast<  ::maglev::MagLevString >::cast(keys->get(i))->getString();
HXLINE( 229)									map->set(key,this->convertToHaxe(y->get(key)));
HXLINE( 230)									i = (i + 1);
            								}
HXLINE( 232)								return map;
            							}
            							else {
HXLINE( 235)								HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("convertToHaxe: unknown type",4a,83,07,f2)));
            							}
            						}
            					}
            				}
            			}
            		}
HXLINE( 197)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC1(Persistence_obj,convertToHaxe,return )

 ::maglev::MagLevAny Persistence_obj::convertToMagLev( ::Dynamic x){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_240_convertToMagLev)
HXDLIN( 240)		if (::hx::IsNull( x )) {
HXLINE( 241)			return ::maglev::MagLevNull_obj::create();
            		}
            		else {
HXLINE( 243)			if (::Std_obj::isOfType(x,( ( ::Dynamic)(::hx::ClassOf< bool >()) ))) {
HXLINE( 244)				return ::maglev::MagLevBoolean_obj::fromBool(::hx::TCast< bool >::cast(x));
            			}
            			else {
HXLINE( 246)				if (::Std_obj::isOfType(x,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
HXLINE( 247)					return ::maglev::MagLevString_obj::fromString(::hx::TCast< ::String >::cast(x));
            				}
            				else {
HXLINE( 249)					if (::Std_obj::isOfType(x,( ( ::Dynamic)(::hx::ClassOf< int >()) ))) {
HXLINE( 250)						return ::maglev::MagLevNumber_obj::fromInt(::hx::TCast< int >::cast(x));
            					}
            					else {
HXLINE( 252)						if (::Std_obj::isOfType(x,( ( ::Dynamic)(::hx::ClassOf< ::Float >()) ))) {
HXLINE( 253)							return ::maglev::MagLevNumber_obj::fromFloat(( (Float)(x) ));
            						}
            						else {
HXLINE( 255)							if (::Std_obj::isOfType(x,( ( ::Dynamic)(::hx::ArrayBase::__mClass) ))) {
HXLINE( 256)								 ::maglev::MagLevArray arr = ::maglev::MagLevArray_obj::create();
HXLINE( 257)								::cpp::VirtualArray y = ( (::cpp::VirtualArray)(x) );
HXLINE( 258)								{
HXLINE( 258)									int _g = 0;
HXDLIN( 258)									while((_g < y->get_length())){
HXLINE( 258)										 ::Dynamic item = y->__get(_g);
HXDLIN( 258)										_g = (_g + 1);
HXLINE( 259)										arr->push(this->convertToMagLev(item));
            									}
            								}
HXLINE( 261)								return arr;
            							}
            							else {
HXLINE( 263)								if (::Std_obj::isOfType(x,( ( ::Dynamic)(::hx::ClassOf< ::haxe::ds::StringMap >()) ))) {
HXLINE( 264)									 ::haxe::ds::StringMap map = ( ( ::haxe::ds::StringMap)(x) );
HXLINE( 265)									 ::maglev::MagLevObject obj = ::maglev::MagLevObject_obj::create();
HXLINE( 266)									{
HXLINE( 266)										 ::Dynamic key = map->keys();
HXDLIN( 266)										while(( (bool)(key->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 266)											::String key1 = ( (::String)(key->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 267)											obj->set(key1,this->convertToMagLev(map->get(key1)));
            										}
            									}
HXLINE( 269)									return obj;
            								}
            								else {
HXLINE( 271)									if (::Reflect_obj::isObject(x)) {
HXLINE( 272)										 ::maglev::MagLevObject obj = ::maglev::MagLevObject_obj::create();
HXLINE( 273)										{
HXLINE( 273)											int _g = 0;
HXDLIN( 273)											::Array< ::String > _g1 = ::Reflect_obj::fields(x);
HXDLIN( 273)											while((_g < _g1->length)){
HXLINE( 273)												::String field = _g1->__get(_g);
HXDLIN( 273)												_g = (_g + 1);
HXLINE( 274)												 ::Dynamic val = ::Reflect_obj::getProperty(x,field);
HXLINE( 275)												obj->set(field,this->convertToMagLev(val));
            											}
            										}
HXLINE( 277)										return obj;
            									}
            									else {
HXLINE( 279)										if (::Reflect_obj::isFunction(x)) {
HXLINE( 280)											 ::Dynamic f = x;
HXLINE( 281)											return ::maglev::MagLevFunction_obj::fromFunction(f);
            										}
            										else {
HXLINE( 284)											HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("convertToMagLev: unknown type",ae,84,a9,64)));
            										}
            									}
            								}
            							}
            						}
            					}
            				}
            			}
            		}
HXLINE( 240)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC1(Persistence_obj,convertToMagLev,return )


::hx::ObjectPtr< Persistence_obj > Persistence_obj::__new( ::maglev::MagLev bus) {
	::hx::ObjectPtr< Persistence_obj > __this = new Persistence_obj();
	__this->__construct(bus);
	return __this;
}

::hx::ObjectPtr< Persistence_obj > Persistence_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev bus) {
	Persistence_obj *__this = (Persistence_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Persistence_obj), true, "persistence.Persistence"));
	*(void **)__this = Persistence_obj::_hx_vtable;
	__this->__construct(bus);
	return __this;
}

Persistence_obj::Persistence_obj()
{
}

void Persistence_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Persistence);
	HX_MARK_MEMBER_NAME(mutators,"mutators");
	HX_MARK_MEMBER_NAME(getters,"getters");
	HX_MARK_MEMBER_NAME(maglev,"maglev");
	HX_MARK_END_CLASS();
}

void Persistence_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(mutators,"mutators");
	HX_VISIT_MEMBER_NAME(getters,"getters");
	HX_VISIT_MEMBER_NAME(maglev,"maglev");
}

::hx::Val Persistence_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { return ::hx::Val( maglev ); }
		if (HX_FIELD_EQ(inName,"mutate") ) { return ::hx::Val( mutate_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"getters") ) { return ::hx::Val( getters ); }
		if (HX_FIELD_EQ(inName,"calcKey") ) { return ::hx::Val( calcKey_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"mutators") ) { return ::hx::Val( mutators ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"addGetter") ) { return ::hx::Val( addGetter_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"addMutator") ) { return ::hx::Val( addMutator_dyn() ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"convertToHaxe") ) { return ::hx::Val( convertToHaxe_dyn() ); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"convertToMagLev") ) { return ::hx::Val( convertToMagLev_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Persistence_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { maglev=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"getters") ) { getters=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"mutators") ) { mutators=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Persistence_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("mutators",51,5b,0f,e4));
	outFields->push(HX_("getters",08,4b,a3,34));
	outFields->push(HX_("maglev",2a,df,2b,b3));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Persistence_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(Persistence_obj,mutators),HX_("mutators",51,5b,0f,e4)},
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(Persistence_obj,getters),HX_("getters",08,4b,a3,34)},
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(Persistence_obj,maglev),HX_("maglev",2a,df,2b,b3)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Persistence_obj_sStaticStorageInfo = 0;
#endif

static ::String Persistence_obj_sMemberFields[] = {
	HX_("mutators",51,5b,0f,e4),
	HX_("getters",08,4b,a3,34),
	HX_("maglev",2a,df,2b,b3),
	HX_("addMutator",c1,56,e0,ee),
	HX_("addGetter",0c,14,64,5b),
	HX_("mutate",86,f3,be,3f),
	HX_("get",96,80,4e,00),
	HX_("calcKey",0a,f4,5a,4e),
	HX_("convertToHaxe",94,89,1b,b6),
	HX_("convertToMagLev",f8,a3,b9,0f),
	::String(null()) };

::hx::Class Persistence_obj::__mClass;

void Persistence_obj::__register()
{
	Persistence_obj _hx_dummy;
	Persistence_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("persistence.Persistence",b0,8b,d5,e5);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Persistence_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Persistence_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Persistence_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Persistence_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Persistence_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_10_boot)
HXDLIN(  10)		__mClass->__meta__ =  ::Dynamic(::hx::Anon_obj::Create(1)
            			->setFixed(0,HX_("obj",f7,8f,54,00), ::Dynamic(::hx::Anon_obj::Create(1)
            				->setFixed(0,HX_("SuppressWarnings",0c,d3,d2,00),::cpp::VirtualArray_obj::__new(1)->init(0,::cpp::VirtualArray_obj::__new(4)->init(0,HX_("checkstyle:FieldDocComment",70,56,1b,20))->init(1,HX_("checkstyle:LocalVariableName",c1,ac,a3,03))->init(2,HX_("checkstyle:MultipleStringLiterals",d6,ed,13,79))->init(3,HX_("checkstyle:MagicNumber",a5,aa,f4,8b)))))));
            	}
}

} // end namespace persistence
