// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_869a921fcf5bba54
#define INCLUDED_869a921fcf5bba54
#include "maglev/MagLevAny.h"
#endif
#ifndef INCLUDED_20db69a30a45e926
#define INCLUDED_20db69a30a45e926
#include "maglev/MagLevArray.h"
#endif
#ifndef INCLUDED_35ec03520fbb0747
#define INCLUDED_35ec03520fbb0747
#include "maglev/MagLevBoolean.h"
#endif
#ifndef INCLUDED_d8a74f90a5c0b964
#define INCLUDED_d8a74f90a5c0b964
#include "maglev/MagLevError.h"
#endif
#ifndef INCLUDED_7f9204b932c8d809
#define INCLUDED_7f9204b932c8d809
#include "maglev/MagLevFunction.h"
#endif
#ifndef INCLUDED_ba46386e6aba7150
#define INCLUDED_ba46386e6aba7150
#include "maglev/MagLevNull.h"
#endif
#ifndef INCLUDED_65acb6100057af6e
#define INCLUDED_65acb6100057af6e
#include "maglev/MagLevResult.h"
#endif
#ifndef INCLUDED_c859d2752ef86c43
#define INCLUDED_c859d2752ef86c43
#include "maglev/MagLevString.h"
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_persistence_MagLevConverter
#include <persistence/MagLevConverter.h>
#endif
#ifndef INCLUDED_persistence_Persistence
#include <persistence/Persistence.h>
#endif
#ifndef INCLUDED_persistence__Persistence_Getter
#include <persistence/_Persistence/Getter.h>
#endif
#ifndef INCLUDED_persistence__Persistence_Mutator
#include <persistence/_Persistence/Mutator.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_22_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",22,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_37_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",37,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_62_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",62,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_56_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",56,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_72_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",72,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_66_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",66,0x9767c4cf)
HX_DEFINE_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_18_new,"persistence.Persistence","new",0x1c38c4a2,"persistence.Persistence.new","persistence/Persistence.hx",18,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_78_addMutator,"persistence.Persistence","addMutator",0xab434ebf,"persistence.Persistence.addMutator","persistence/Persistence.hx",78,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_80_addMutator,"persistence.Persistence","addMutator",0xab434ebf,"persistence.Persistence.addMutator","persistence/Persistence.hx",80,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_89_addGetter,"persistence.Persistence","addGetter",0xa800a5ce,"persistence.Persistence.addGetter","persistence/Persistence.hx",89,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_91_addGetter,"persistence.Persistence","addGetter",0xa800a5ce,"persistence.Persistence.addGetter","persistence/Persistence.hx",91,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_94_addGetter,"persistence.Persistence","addGetter",0xa800a5ce,"persistence.Persistence.addGetter","persistence/Persistence.hx",94,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_103_mutate,"persistence.Persistence","mutate",0x1e0a9484,"persistence.Persistence.mutate","persistence/Persistence.hx",103,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_110_mutate,"persistence.Persistence","mutate",0x1e0a9484,"persistence.Persistence.mutate","persistence/Persistence.hx",110,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_109_mutate,"persistence.Persistence","mutate",0x1e0a9484,"persistence.Persistence.mutate","persistence/Persistence.hx",109,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_119_get,"persistence.Persistence","get",0x1c3374d8,"persistence.Persistence.get","persistence/Persistence.hx",119,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_126_get,"persistence.Persistence","get",0x1c3374d8,"persistence.Persistence.get","persistence/Persistence.hx",126,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_125_get,"persistence.Persistence","get",0x1c3374d8,"persistence.Persistence.get","persistence/Persistence.hx",125,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_124_get,"persistence.Persistence","get",0x1c3374d8,"persistence.Persistence.get","persistence/Persistence.hx",124,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_137_calcKey,"persistence.Persistence","calcKey",0xf23c314c,"persistence.Persistence.calcKey","persistence/Persistence.hx",137,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_141_convertToHaxe,"persistence.Persistence","convertToHaxe",0x4e912456,"persistence.Persistence.convertToHaxe","persistence/Persistence.hx",141,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_145_convertToMagLev,"persistence.Persistence","convertToMagLev",0xe4dcf33a,"persistence.Persistence.convertToMagLev","persistence/Persistence.hx",145,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_148_mapUpdate,"persistence.Persistence","mapUpdate",0xb6817387,"persistence.Persistence.mapUpdate","persistence/Persistence.hx",148,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_153_mapUpdate,"persistence.Persistence","mapUpdate",0xb6817387,"persistence.Persistence.mapUpdate","persistence/Persistence.hx",153,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_161_mapUpdate,"persistence.Persistence","mapUpdate",0xb6817387,"persistence.Persistence.mapUpdate","persistence/Persistence.hx",161,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_163_mapUpdate,"persistence.Persistence","mapUpdate",0xb6817387,"persistence.Persistence.mapUpdate","persistence/Persistence.hx",163,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_173_update,"persistence.Persistence","update",0x65512707,"persistence.Persistence.update","persistence/Persistence.hx",173,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_178_update,"persistence.Persistence","update",0x65512707,"persistence.Persistence.update","persistence/Persistence.hx",178,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_190_update,"persistence.Persistence","update",0x65512707,"persistence.Persistence.update","persistence/Persistence.hx",190,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_192_update,"persistence.Persistence","update",0x65512707,"persistence.Persistence.update","persistence/Persistence.hx",192,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_202_mapQuery,"persistence.Persistence","mapQuery",0x9661574a,"persistence.Persistence.mapQuery","persistence/Persistence.hx",202,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_207_mapQuery,"persistence.Persistence","mapQuery",0x9661574a,"persistence.Persistence.mapQuery","persistence/Persistence.hx",207,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_215_mapQuery,"persistence.Persistence","mapQuery",0x9661574a,"persistence.Persistence.mapQuery","persistence/Persistence.hx",215,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_217_mapQuery,"persistence.Persistence","mapQuery",0x9661574a,"persistence.Persistence.mapQuery","persistence/Persistence.hx",217,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_227_query,"persistence.Persistence","query",0xf42693ca,"persistence.Persistence.query","persistence/Persistence.hx",227,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_233_query,"persistence.Persistence","query",0xf42693ca,"persistence.Persistence.query","persistence/Persistence.hx",233,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_245_query,"persistence.Persistence","query",0xf42693ca,"persistence.Persistence.query","persistence/Persistence.hx",245,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_247_query,"persistence.Persistence","query",0xf42693ca,"persistence.Persistence.query","persistence/Persistence.hx",247,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_257_mapResults,"persistence.Persistence","mapResults",0xc84b39b8,"persistence.Persistence.mapResults","persistence/Persistence.hx",257,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_262_mapResults,"persistence.Persistence","mapResults",0xc84b39b8,"persistence.Persistence.mapResults","persistence/Persistence.hx",262,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_270_mapResults,"persistence.Persistence","mapResults",0xc84b39b8,"persistence.Persistence.mapResults","persistence/Persistence.hx",270,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_272_mapResults,"persistence.Persistence","mapResults",0xc84b39b8,"persistence.Persistence.mapResults","persistence/Persistence.hx",272,0x9767c4cf)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0a59171cb4a4c9_12_boot,"persistence.Persistence","boot",0x8d8c49b0,"persistence.Persistence.boot","persistence/Persistence.hx",12,0x9767c4cf)
namespace persistence{

void Persistence_obj::__construct( ::maglev::MagLev bus){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_22_new)
HXLINE(  23)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  24)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  25)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  25)			 ::Dynamic strategyMethod = _gthis1->convertToHaxe(args->get(2));
HXLINE(  26)			 ::Dynamic updateMapper = null();
HXLINE(  27)			if ((args->size() > 3)) {
HXLINE(  28)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  28)				updateMapper = _gthis1->convertToHaxe(args->get(3));
            			}
HXLINE(  30)			 ::Dynamic useRecordDataAsParams = null();
HXLINE(  31)			if ((args->size() > 4)) {
HXLINE(  32)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  32)				useRecordDataAsParams = _gthis1->convertToHaxe(args->get(4));
            			}
HXLINE(  34)			_gthis->addMutator(recordType,operationName,strategyMethod,updateMapper,useRecordDataAsParams);
HXLINE(  35)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevBoolean_obj::fromBool(true));
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_1, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_37_new)
HXLINE(  38)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  39)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  40)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  40)			 ::Dynamic strategyMethod = _gthis1->convertToHaxe(args->get(2));
HXLINE(  41)			 ::Dynamic queryMapper = null();
HXLINE(  42)			if ((args->size() >= 4)) {
HXLINE(  43)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  43)				queryMapper = _gthis1->convertToHaxe(args->get(3));
            			}
HXLINE(  45)			 ::Dynamic resultMapper = null();
HXLINE(  46)			if ((args->size() >= 5)) {
HXLINE(  47)				 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  47)				resultMapper = _gthis1->convertToHaxe(args->get(4));
            			}
HXLINE(  49)			 ::Dynamic useQueryValuesAsParams = null();
HXLINE(  50)			if ((args->size() >= 6)) {
HXLINE(  51)				useQueryValuesAsParams = ::hx::TCast<  ::maglev::MagLevBoolean >::cast(args->get(5))->getBool();
            			}
HXLINE(  53)			_gthis->addGetter(recordType,operationName,strategyMethod,queryMapper,resultMapper,useQueryValuesAsParams);
HXLINE(  54)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevBoolean_obj::fromBool(true));
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_3, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_2, ::maglev::MagLevResult,maglevResult, ::persistence::Persistence,_gthis) HXARGC(1)
            			void _hx_run( ::Dynamic haxeResult){
            				HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_62_new)
HXLINE(  62)				 ::maglev::MagLevResult maglevResult1 = maglevResult;
HXDLIN(  62)				maglevResult1->setResult(_gthis->convertToMagLev(haxeResult));
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_56_new)
HXLINE(  57)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  58)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  59)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  59)			 ::Dynamic recordData = _gthis1->convertToHaxe(args->get(2));
HXLINE(  60)			 ::maglev::MagLevResult maglevResult = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  61)			_gthis->mutate(recordType,operationName,recordData, ::Dynamic(new _hx_Closure_2(maglevResult,_gthis)));
HXLINE(  64)			return maglevResult;
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_5, ::persistence::Persistence,_gthis) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevArray args){
            			HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_4, ::maglev::MagLevResult,maglevResult, ::persistence::Persistence,_gthis) HXARGC(1)
            			void _hx_run( ::Dynamic haxeResult){
            				HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_72_new)
HXLINE(  72)				 ::maglev::MagLevResult maglevResult1 = maglevResult;
HXDLIN(  72)				maglevResult1->setResult(_gthis->convertToMagLev(haxeResult));
            			}
            			HX_END_LOCAL_FUNC1((void))

            			HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_66_new)
HXLINE(  67)			::String recordType = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(0))->getString();
HXLINE(  68)			::String operationName = ::hx::TCast<  ::maglev::MagLevString >::cast(args->get(1))->getString();
HXLINE(  69)			 ::persistence::Persistence _gthis1 = _gthis;
HXDLIN(  69)			 ::Dynamic queryValues = _gthis1->convertToHaxe(args->get(2));
HXLINE(  70)			 ::maglev::MagLevResult maglevResult = ::maglev::MagLevResult_obj::createAsync();
HXLINE(  71)			_gthis->get(recordType,operationName,queryValues, ::Dynamic(new _hx_Closure_4(maglevResult,_gthis)));
HXLINE(  74)			return maglevResult;
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_18_new)
HXDLIN(  18)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE(  19)		this->mutators =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  20)		this->getters =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  21)		this->maglev = bus;
HXLINE(  22)		 ::maglev::MagLev _hx_tmp = this->maglev;
HXDLIN(  22)		_hx_tmp->_hx_register(HX_("Persistence.AddMutator",b0,4b,5e,d4),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_0(_gthis))));
HXLINE(  37)		 ::maglev::MagLev _hx_tmp1 = this->maglev;
HXDLIN(  37)		_hx_tmp1->_hx_register(HX_("Persistence.AddGetter",fd,51,1c,b7),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_1(_gthis))));
HXLINE(  56)		 ::maglev::MagLev _hx_tmp2 = this->maglev;
HXDLIN(  56)		_hx_tmp2->_hx_register(HX_("Persistence.Mutate",f5,04,66,8c),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_3(_gthis))));
HXLINE(  66)		 ::maglev::MagLev _hx_tmp3 = this->maglev;
HXDLIN(  66)		_hx_tmp3->_hx_register(HX_("Persistence.Get",c7,c3,56,12),::maglev::MagLevFunction_obj::fromFunction( ::Dynamic(new _hx_Closure_5(_gthis))));
            	}

Dynamic Persistence_obj::__CreateEmpty() { return new Persistence_obj; }

void *Persistence_obj::_hx_vtable = 0;

Dynamic Persistence_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Persistence_obj > _hx_result = new Persistence_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Persistence_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x0263bb48;
}

void Persistence_obj::addMutator(::String recordType,::String operationName, ::Dynamic strategyMethod, ::Dynamic updateMapper, ::Dynamic useRecordDataAsParams){
            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_78_addMutator)
HXLINE(  79)		if (::hx::IsNull( updateMapper )) {
            			HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(2)
            			void _hx_run( ::Dynamic v, ::Dynamic cb){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_80_addMutator)
HXLINE(  80)				cb(v);
            			}
            			HX_END_LOCAL_FUNC2((void))

HXLINE(  80)			updateMapper =  ::Dynamic(new _hx_Closure_0());
            		}
HXLINE(  82)		if (::hx::IsNull( useRecordDataAsParams )) {
HXLINE(  83)			useRecordDataAsParams = false;
            		}
HXLINE(  85)		 ::persistence::_Persistence::Mutator mutator =  ::persistence::_Persistence::Mutator_obj::__alloc( HX_CTX ,recordType,strategyMethod,updateMapper,( (bool)(useRecordDataAsParams) ));
HXLINE(  86)		{
HXLINE(  86)			::Dynamic this1 = this->mutators;
HXDLIN(  86)			( ( ::haxe::ds::StringMap)(this1) )->set(this->calcKey(recordType,operationName),mutator);
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC5(Persistence_obj,addMutator,(void))

void Persistence_obj::addGetter(::String recordType,::String operationName, ::Dynamic strategyMethod, ::Dynamic queryMapper, ::Dynamic resultMapper, ::Dynamic useQueryValuesAsParams){
            	HX_GC_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_89_addGetter)
HXLINE(  90)		if (::hx::IsNull( queryMapper )) {
            			HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(2)
            			void _hx_run( ::Dynamic v, ::Dynamic cb){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_91_addGetter)
HXLINE(  91)				cb(v);
            			}
            			HX_END_LOCAL_FUNC2((void))

HXLINE(  91)			queryMapper =  ::Dynamic(new _hx_Closure_0());
            		}
HXLINE(  93)		if (::hx::IsNull( resultMapper )) {
            			HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(2)
            			void _hx_run( ::Dynamic v, ::Dynamic cb){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_94_addGetter)
HXLINE(  94)				cb(v);
            			}
            			HX_END_LOCAL_FUNC2((void))

HXLINE(  94)			resultMapper =  ::Dynamic(new _hx_Closure_1());
            		}
HXLINE(  96)		if (::hx::IsNull( useQueryValuesAsParams )) {
HXLINE(  97)			useQueryValuesAsParams = false;
            		}
HXLINE(  99)		 ::persistence::_Persistence::Getter getter =  ::persistence::_Persistence::Getter_obj::__alloc( HX_CTX ,recordType,strategyMethod,queryMapper,resultMapper,( (bool)(useQueryValuesAsParams) ));
HXLINE( 100)		{
HXLINE( 100)			::Dynamic this1 = this->getters;
HXDLIN( 100)			( ( ::haxe::ds::StringMap)(this1) )->set(this->calcKey(recordType,operationName),getter);
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC6(Persistence_obj,addGetter,(void))

void Persistence_obj::mutate(::String recordType,::String operationName, ::Dynamic recordData, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_103_mutate)
HXDLIN( 103)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 106)		::Dynamic this1 = this->mutators;
HXDLIN( 106)		if (( ( ::haxe::ds::StringMap)(this1) )->exists(this->calcKey(recordType,operationName))) {
            			HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_1, ::persistence::Persistence,_gthis, ::persistence::_Persistence::Mutator,mutator, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic mappedRecordData){
            				HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            				void _hx_run( ::Dynamic updateResults){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_110_mutate)
HXLINE( 110)					callback(updateResults);
            				}
            				HX_END_LOCAL_FUNC1((void))

            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_109_mutate)
HXLINE( 109)				_gthis->update(mutator,mappedRecordData, ::Dynamic(new _hx_Closure_0(callback)));
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 107)			::Dynamic this1 = this->mutators;
HXDLIN( 107)			 ::persistence::_Persistence::Mutator mutator = ( ( ::persistence::_Persistence::Mutator)(( ( ::haxe::ds::StringMap)(this1) )->get(this->calcKey(recordType,operationName))) );
HXLINE( 108)			this->mapUpdate(mutator,recordData, ::Dynamic(new _hx_Closure_1(_gthis,mutator,callback)));
            		}
            		else {
HXLINE( 115)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("the specified mutator has not been added",fc,3b,68,3f)));
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC4(Persistence_obj,mutate,(void))

void Persistence_obj::get(::String recordType,::String operationName, ::Dynamic queryValues, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_119_get)
HXDLIN( 119)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 120)		::Dynamic this1 = this->getters;
HXDLIN( 120)		if (( ( ::haxe::ds::StringMap)(this1) )->exists(this->calcKey(recordType,operationName))) {
            			HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis, ::persistence::_Persistence::Getter,getter, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic mappedQueryValues){
            				HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_1, ::persistence::Persistence,_gthis, ::persistence::_Persistence::Getter,getter, ::Dynamic,callback) HXARGC(1)
            				void _hx_run( ::Dynamic queryResults){
            					HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            					void _hx_run( ::Dynamic mappedQueryValues){
            						HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_126_get)
HXLINE( 126)						callback(mappedQueryValues);
            					}
            					HX_END_LOCAL_FUNC1((void))

            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_125_get)
HXLINE( 125)					_gthis->mapResults(getter,queryResults, ::Dynamic(new _hx_Closure_0(callback)));
            				}
            				HX_END_LOCAL_FUNC1((void))

            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_124_get)
HXLINE( 124)				_gthis->query(getter,mappedQueryValues, ::Dynamic(new _hx_Closure_1(_gthis,getter,callback)));
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 121)			::Dynamic this1 = this->getters;
HXDLIN( 121)			 ::persistence::_Persistence::Getter getter = ( ( ::persistence::_Persistence::Getter)(( ( ::haxe::ds::StringMap)(this1) )->get(this->calcKey(recordType,operationName))) );
HXLINE( 123)			this->mapQuery(getter,queryValues, ::Dynamic(new _hx_Closure_2(_gthis,getter,callback)));
            		}
            		else {
HXLINE( 132)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("the specified getter has not been added",55,b4,c1,d8)));
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC4(Persistence_obj,get,(void))

::String Persistence_obj::calcKey(::String recordType,::String operationName){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_137_calcKey)
HXDLIN( 137)		return ((recordType + HX_(".",2e,00,00,00)) + operationName);
            	}


HX_DEFINE_DYNAMIC_FUNC2(Persistence_obj,calcKey,return )

 ::Dynamic Persistence_obj::convertToHaxe( ::maglev::MagLevAny x){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_141_convertToHaxe)
HXDLIN( 141)		return ::persistence::MagLevConverter_obj::convertToHaxe(x);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Persistence_obj,convertToHaxe,return )

 ::maglev::MagLevAny Persistence_obj::convertToMagLev( ::Dynamic x){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_145_convertToMagLev)
HXDLIN( 145)		return ::persistence::MagLevConverter_obj::convertToMagLev(x);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Persistence_obj,convertToMagLev,return )

void Persistence_obj::mapUpdate( ::persistence::_Persistence::Mutator mutator, ::Dynamic recordData, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_148_mapUpdate)
HXDLIN( 148)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 150)		if (::Reflect_obj::isFunction(mutator->updateMapper)) {
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic params){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_153_mapUpdate)
HXLINE( 153)				callback(params);
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 151)			 ::Dynamic updateMapper = mutator->updateMapper;
HXLINE( 152)			updateMapper(recordData, ::Dynamic(new _hx_Closure_0(callback)));
            		}
            		else {
HXLINE( 156)			if (::Std_obj::isOfType(mutator->updateMapper,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
            				HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError error){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_161_mapUpdate)
HXLINE( 161)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(error->getMessage()));
HXDLIN( 161)					return null();
            				}
            				HX_END_LOCAL_FUNC1(return)

            				HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis, ::Dynamic,callback) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny result){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_163_mapUpdate)
HXLINE( 164)					 ::Dynamic callback1 = callback;
HXDLIN( 164)					callback1(_gthis->convertToHaxe(result));
HXLINE( 165)					return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            				}
            				HX_END_LOCAL_FUNC1(return)

HXLINE( 157)				::String updateMapper = ( (::String)(mutator->updateMapper) );
HXLINE( 159)				 ::maglev::MagLev ret = this->maglev;
HXDLIN( 159)				 ::maglev::MagLevResult ret1 = ret->call(updateMapper,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,recordData))));
HXLINE( 160)				ret1->onError( ::Dynamic(new _hx_Closure_1()));
HXLINE( 163)				ret1->onResult( ::Dynamic(new _hx_Closure_2(_gthis,callback)));
            			}
            			else {
HXLINE( 169)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("updateMapper must be a string or function",e1,0d,80,87)));
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,mapUpdate,(void))

void Persistence_obj::update( ::persistence::_Persistence::Mutator mutator, ::Dynamic recordData, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_173_update)
HXDLIN( 173)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 175)		if (::Reflect_obj::isFunction(mutator->strategyMethod)) {
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic raw_result){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_178_update)
HXLINE( 178)				callback(raw_result);
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 176)			 ::Dynamic strategyMethod = mutator->strategyMethod;
HXLINE( 177)			strategyMethod(recordData, ::Dynamic(new _hx_Closure_0(callback)));
            		}
            		else {
HXLINE( 181)			if (::Std_obj::isOfType(mutator->strategyMethod,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
            				HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError error){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_190_update)
HXLINE( 190)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(error->getMessage()));
HXDLIN( 190)					return null();
            				}
            				HX_END_LOCAL_FUNC1(return)

            				HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis, ::Dynamic,callback) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny result){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_192_update)
HXLINE( 193)					 ::Dynamic callback1 = callback;
HXDLIN( 193)					callback1(_gthis->convertToHaxe(result));
HXLINE( 194)					return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            				}
            				HX_END_LOCAL_FUNC1(return)

HXLINE( 182)				::String strategyMethod = ( (::String)(mutator->strategyMethod) );
HXLINE( 183)				 ::maglev::MagLevResult raw_maglev_result;
HXLINE( 184)				if (mutator->useRecordDataAsParams) {
HXLINE( 185)					 ::maglev::MagLev raw_maglev_result1 = this->maglev;
HXDLIN( 185)					raw_maglev_result = raw_maglev_result1->call(strategyMethod,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(recordData)));
            				}
            				else {
HXLINE( 187)					 ::maglev::MagLev raw_maglev_result1 = this->maglev;
HXDLIN( 187)					raw_maglev_result = raw_maglev_result1->call(strategyMethod,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,recordData))));
            				}
HXLINE( 189)				raw_maglev_result->onError( ::Dynamic(new _hx_Closure_1()));
HXLINE( 192)				raw_maglev_result->onResult( ::Dynamic(new _hx_Closure_2(_gthis,callback)));
            			}
            			else {
HXLINE( 198)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("strategyMethod must be a string or function",97,7a,0d,90)));
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,update,(void))

void Persistence_obj::mapQuery( ::persistence::_Persistence::Getter getter, ::Dynamic queryValues, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_202_mapQuery)
HXDLIN( 202)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 204)		if (::Reflect_obj::isFunction(getter->queryMapper)) {
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic mappedQueryValues){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_207_mapQuery)
HXLINE( 207)				callback(mappedQueryValues);
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 205)			 ::Dynamic queryMapper = getter->queryMapper;
HXLINE( 206)			queryMapper(queryValues, ::Dynamic(new _hx_Closure_0(callback)));
            		}
            		else {
HXLINE( 210)			if (::Std_obj::isOfType(getter->queryMapper,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
            				HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError error){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_215_mapQuery)
HXLINE( 215)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(error->getMessage()));
HXDLIN( 215)					return null();
            				}
            				HX_END_LOCAL_FUNC1(return)

            				HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis, ::Dynamic,callback) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny result){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_217_mapQuery)
HXLINE( 218)					 ::Dynamic callback1 = callback;
HXDLIN( 218)					callback1(_gthis->convertToHaxe(result));
HXLINE( 219)					return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            				}
            				HX_END_LOCAL_FUNC1(return)

HXLINE( 211)				::String queryMapper = ( (::String)(getter->queryMapper) );
HXLINE( 213)				 ::maglev::MagLev ret = this->maglev;
HXDLIN( 213)				 ::maglev::MagLevResult ret1 = ret->call(queryMapper,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,queryValues))));
HXLINE( 214)				ret1->onError( ::Dynamic(new _hx_Closure_1()));
HXLINE( 217)				ret1->onResult( ::Dynamic(new _hx_Closure_2(_gthis,callback)));
            			}
            			else {
HXLINE( 223)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("queryMapper must be a string or function",42,16,bc,ef)));
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,mapQuery,(void))

void Persistence_obj::query( ::persistence::_Persistence::Getter getter, ::Dynamic queryValues, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_227_query)
HXDLIN( 227)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 229)		 ::Dynamic raw_result = null();
HXLINE( 230)		if (::Reflect_obj::isFunction(getter->strategyMethod)) {
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic raw_result){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_233_query)
HXLINE( 233)				callback(raw_result);
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 231)			 ::Dynamic strategyMethod = getter->strategyMethod;
HXLINE( 232)			strategyMethod(queryValues, ::Dynamic(new _hx_Closure_0(callback)));
            		}
            		else {
HXLINE( 236)			if (::Std_obj::isOfType(getter->strategyMethod,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
            				HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError error){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_245_query)
HXLINE( 245)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(error->getMessage()));
HXDLIN( 245)					return null();
            				}
            				HX_END_LOCAL_FUNC1(return)

            				HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis, ::Dynamic,callback) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny result){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_247_query)
HXLINE( 248)					 ::Dynamic callback1 = callback;
HXDLIN( 248)					callback1(_gthis->convertToHaxe(result));
HXLINE( 249)					return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            				}
            				HX_END_LOCAL_FUNC1(return)

HXLINE( 237)				::String strategyMethod = ( (::String)(getter->strategyMethod) );
HXLINE( 238)				 ::maglev::MagLevResult raw_maglev_result;
HXLINE( 239)				if (getter->useQueryValuesAsParams) {
HXLINE( 240)					 ::maglev::MagLev raw_maglev_result1 = this->maglev;
HXDLIN( 240)					::String getter1 = ( (::String)(getter->strategyMethod) );
HXDLIN( 240)					raw_maglev_result = raw_maglev_result1->call(getter1,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(queryValues)));
            				}
            				else {
HXLINE( 242)					 ::maglev::MagLev raw_maglev_result1 = this->maglev;
HXDLIN( 242)					::String getter1 = ( (::String)(getter->strategyMethod) );
HXDLIN( 242)					raw_maglev_result = raw_maglev_result1->call(getter1,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,queryValues))));
            				}
HXLINE( 244)				raw_maglev_result->onError( ::Dynamic(new _hx_Closure_1()));
HXLINE( 247)				raw_maglev_result->onResult( ::Dynamic(new _hx_Closure_2(_gthis,callback)));
            			}
            			else {
HXLINE( 253)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("strategyMethod must be a string or function",97,7a,0d,90)));
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,query,(void))

void Persistence_obj::mapResults( ::persistence::_Persistence::Getter getter, ::Dynamic queryResults, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_257_mapResults)
HXDLIN( 257)		 ::persistence::Persistence _gthis = ::hx::ObjectPtr<OBJ_>(this);
HXLINE( 259)		if (::Reflect_obj::isFunction(getter->resultMapper)) {
            			HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            			void _hx_run( ::Dynamic mappedResults){
            				HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_262_mapResults)
HXLINE( 262)				callback(mappedResults);
            			}
            			HX_END_LOCAL_FUNC1((void))

HXLINE( 260)			 ::Dynamic resultMapper = getter->resultMapper;
HXLINE( 261)			resultMapper(queryResults, ::Dynamic(new _hx_Closure_0(callback)));
            		}
            		else {
HXLINE( 265)			if (::Std_obj::isOfType(getter->resultMapper,( ( ::Dynamic)(::hx::ClassOf< ::String >()) ))) {
            				HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError error){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_270_mapResults)
HXLINE( 270)					HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(error->getMessage()));
HXDLIN( 270)					return null();
            				}
            				HX_END_LOCAL_FUNC1(return)

            				HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_2, ::persistence::Persistence,_gthis, ::Dynamic,callback) HXARGC(1)
            				 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny result){
            					HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_272_mapResults)
HXLINE( 273)					 ::Dynamic callback1 = callback;
HXDLIN( 273)					callback1(_gthis->convertToHaxe(result));
HXLINE( 274)					return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            				}
            				HX_END_LOCAL_FUNC1(return)

HXLINE( 266)				::String resultMapper = ( (::String)(getter->resultMapper) );
HXLINE( 268)				 ::maglev::MagLev maglev_result = this->maglev;
HXDLIN( 268)				 ::maglev::MagLevResult maglev_result1 = maglev_result->call(resultMapper,::hx::TCast<  ::maglev::MagLevArray >::cast(this->convertToMagLev(::cpp::VirtualArray_obj::__new(1)->init(0,queryResults))));
HXLINE( 269)				maglev_result1->onError( ::Dynamic(new _hx_Closure_1()));
HXLINE( 272)				maglev_result1->onResult( ::Dynamic(new _hx_Closure_2(_gthis,callback)));
            			}
            			else {
HXLINE( 278)				HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(HX_("resultMapper must be a string or function",8d,d7,71,1d)));
            			}
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC3(Persistence_obj,mapResults,(void))


::hx::ObjectPtr< Persistence_obj > Persistence_obj::__new( ::maglev::MagLev bus) {
	::hx::ObjectPtr< Persistence_obj > __this = new Persistence_obj();
	__this->__construct(bus);
	return __this;
}

::hx::ObjectPtr< Persistence_obj > Persistence_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev bus) {
	Persistence_obj *__this = (Persistence_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Persistence_obj), true, "persistence.Persistence"));
	*(void **)__this = Persistence_obj::_hx_vtable;
	__this->__construct(bus);
	return __this;
}

Persistence_obj::Persistence_obj()
{
}

void Persistence_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Persistence);
	HX_MARK_MEMBER_NAME(mutators,"mutators");
	HX_MARK_MEMBER_NAME(getters,"getters");
	HX_MARK_MEMBER_NAME(maglev,"maglev");
	HX_MARK_END_CLASS();
}

void Persistence_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(mutators,"mutators");
	HX_VISIT_MEMBER_NAME(getters,"getters");
	HX_VISIT_MEMBER_NAME(maglev,"maglev");
}

::hx::Val Persistence_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"query") ) { return ::hx::Val( query_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { return ::hx::Val( maglev ); }
		if (HX_FIELD_EQ(inName,"mutate") ) { return ::hx::Val( mutate_dyn() ); }
		if (HX_FIELD_EQ(inName,"update") ) { return ::hx::Val( update_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"getters") ) { return ::hx::Val( getters ); }
		if (HX_FIELD_EQ(inName,"calcKey") ) { return ::hx::Val( calcKey_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"mutators") ) { return ::hx::Val( mutators ); }
		if (HX_FIELD_EQ(inName,"mapQuery") ) { return ::hx::Val( mapQuery_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"addGetter") ) { return ::hx::Val( addGetter_dyn() ); }
		if (HX_FIELD_EQ(inName,"mapUpdate") ) { return ::hx::Val( mapUpdate_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"addMutator") ) { return ::hx::Val( addMutator_dyn() ); }
		if (HX_FIELD_EQ(inName,"mapResults") ) { return ::hx::Val( mapResults_dyn() ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"convertToHaxe") ) { return ::hx::Val( convertToHaxe_dyn() ); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"convertToMagLev") ) { return ::hx::Val( convertToMagLev_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Persistence_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { maglev=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"getters") ) { getters=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"mutators") ) { mutators=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Persistence_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("mutators",51,5b,0f,e4));
	outFields->push(HX_("getters",08,4b,a3,34));
	outFields->push(HX_("maglev",2a,df,2b,b3));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Persistence_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(Persistence_obj,mutators),HX_("mutators",51,5b,0f,e4)},
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(Persistence_obj,getters),HX_("getters",08,4b,a3,34)},
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(Persistence_obj,maglev),HX_("maglev",2a,df,2b,b3)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Persistence_obj_sStaticStorageInfo = 0;
#endif

static ::String Persistence_obj_sMemberFields[] = {
	HX_("mutators",51,5b,0f,e4),
	HX_("getters",08,4b,a3,34),
	HX_("maglev",2a,df,2b,b3),
	HX_("addMutator",c1,56,e0,ee),
	HX_("addGetter",0c,14,64,5b),
	HX_("mutate",86,f3,be,3f),
	HX_("get",96,80,4e,00),
	HX_("calcKey",0a,f4,5a,4e),
	HX_("convertToHaxe",94,89,1b,b6),
	HX_("convertToMagLev",f8,a3,b9,0f),
	HX_("mapUpdate",c5,e1,e4,69),
	HX_("update",09,86,05,87),
	HX_("mapQuery",cc,fa,2c,d5),
	HX_("query",08,8b,ea,5d),
	HX_("mapResults",ba,41,e8,0b),
	::String(null()) };

::hx::Class Persistence_obj::__mClass;

void Persistence_obj::__register()
{
	Persistence_obj _hx_dummy;
	Persistence_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("persistence.Persistence",b0,8b,d5,e5);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Persistence_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Persistence_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Persistence_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Persistence_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Persistence_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_9b0a59171cb4a4c9_12_boot)
HXDLIN(  12)		__mClass->__meta__ =  ::Dynamic(::hx::Anon_obj::Create(1)
            			->setFixed(0,HX_("obj",f7,8f,54,00), ::Dynamic(::hx::Anon_obj::Create(1)
            				->setFixed(0,HX_("SuppressWarnings",0c,d3,d2,00),::cpp::VirtualArray_obj::__new(1)->init(0,::cpp::VirtualArray_obj::__new(4)->init(0,HX_("checkstyle:FieldDocComment",70,56,1b,20))->init(1,HX_("checkstyle:LocalVariableName",c1,ac,a3,03))->init(2,HX_("checkstyle:MultipleStringLiterals",d6,ed,13,79))->init(3,HX_("checkstyle:MagicNumber",a5,aa,f4,8b)))))));
            	}
}

} // end namespace persistence
